const express = require("express");
const jwt = require("jsonwebtoken");
const bcrypt = require("bcrypt");
const z = require("zod");
const mongoose = require("mongoose");
const { UserModel, TodoModel } = require("./db")
const { auth } = require("./auth");
require("dotenv").config();

const JWT_SECRET = process.env.JWT_SECRET;
const CONNECTION_URL = process.env.CONNECTION_URL;

const app = express();

app.use(express.json());

app.post('/signup', async (req, res) => {
    // cleaner syntax 
    const { email, password, name } = req.body;

    const requiredBody = z.object({
        email: z.email().min(3).max(100) ,
        password: z
                    .string()
                    .min(8, {message: 'password must be atleast 8 chars'}) 
                    .regex(/[a-z]/, {message: 'must contain atleast one lower case char'})
                    .regex(/[A-Z]/, {message: 'must contain atleast one uppercase char'})
                    .regex(/[^A-Za-z0-9]/, {message: 'must contain atleast one special char'}),
        name: z.string()
    })

    // won't throw an exception (unlike parse())
    const parsed = requiredBody.safeParse(req.body);
    if (!parsed.success){
        res.status(400).json({
            message: z.treeifyError(parsed.error)
            // message: z.prettifyError(parsed.error)
        })
        return;
    }

    try {
        // password hashed with salting method, looks something like: 
        // $2b$10$vnD/yp9QuZi9dXTghVZRQu0FHt1QnSYaH85JYpwstyWG78q1fFeO6
        // bcrypt version $ number of iterations of hashing, salt (16 chars), hashed password
        const hashedPassword = await bcrypt.hash(password, 10);

        await UserModel.create({
            email: email, 
            password: hashedPassword,
            name: name
        })

        // if reached here means success 
        res.json({
            message: "You are signed up!"
        })
    } catch(e) {
        // mono gives 11000 code for Duplicate Key error 
        if (e.code === 11000){
            res.status(400).json({
                message: "User already exists with this email. please login"
            })
        } else {
            // something unexpected happened on the server
            res.status(500).json({
                message: "Server Error"
            })
        }
    }
})

app.post('/signin', async (req, res) => {
    const { email, password } = req.body;
    
    // find if such a user exists
    const user = await UserModel.findOne({
        email: email,
    })
    const passwordMatch = await bcrypt.compare(password, user.password);


    if (user && passwordMatch){
        const token = jwt.sign({
            // sign their id - it's unique, generated by mongo, also pretty much useless if someone catches it 
            id: user._id
        }, JWT_SECRET);

        res.json({
            message: "You are successfully Signed In",
            token: token
        })
    } else {
        res.status(403).json({
            message: "Incorrect username and password"
        })
    }
})


// authenticated end points from here 
// uses auth middleware imported from auth.js
// allow logged in user to create a todo 
app.post('/todo', auth, async (req, res) => {
    const id = req.id;
    const { description, done } = req.body;

    try {
        await TodoModel.create({
            description: description, 
            done: done,
            userId: id
        })

        res.json({
            message: "To Do created Successfully"
        })

    } catch (e) {
        console.log(e);
        res.status(500).json({
            message: "Error has occured"
        })
    }
})

app.get('/todos', auth, async (req, res) => {
    const id = req.id;

    try {
        const todos = await TodoModel.find({
            userId: id
        })

        res.json({
            message: "Query executed successfully",
            todos: todos
        })
    } catch (e) {
        console.log(e);
        res.status(500).json({
            message: "Error Occured"
        })
    }
})

// need to specify the db after the / (otherwise goes to test db)

async function main(){
    try {
        await mongoose.connect(CONNECTION_URL);
        console.log("Connected to db successfully")

        app.listen(3000, () => {
            console.log("Server running on port 3000")
        });
    } catch (e){
        console.log(e);
    }
}

main();